import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { client } from "../libs/client";
const inter = Inter({ subsets: ["latin"] });

// データをテンプレートに受け渡す部分の処理を記述します
export const getStaticProps = async () => {
  const data = await client.get({ endpoint: "cms" });

  return {
    props: {
      cms: data.contents,
    },
  };
};

export default function Home({ cms }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>{cms.title}</h1>
        <ul>
          {cms.map((cms) => (
            <li key={cms.id}>
              <Link href={`/cms/${cms.id}`}>{cms.title}</Link>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
}
